# Generated by Django 5.1.3 on 2025-01-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ENNEAGRAM',
            fields=[
                ('enneagram', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descr', models.TextField()),
            ],
            options={
                'db_table': 'enneagram',
            },
        ),
        migrations.CreateModel(
            name='MBTI',
            fields=[
                ('mbtid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('descr', models.TextField()),
                ('descr1', models.TextField()),
                ('descr2', models.TextField()),
                ('descr3', models.TextField()),
                ('descr4', models.TextField()),
            ],
            options={
                'db_table': 'mbti',
            },
        ),
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('nick', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('mbti', models.CharField(max_length=4)),
                ('enneagram', models.CharField(max_length=3)),
                ('birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pwd', models.TextField()),
                ('last_login', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ZODIAC',
            fields=[
                ('sign', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descr', models.TextField()),
            ],
            options={
                'db_table': 'zodiacsign',
            },
        ),
    ]
